"""Packaged Watchman runtime payloads and materialization helpers."""

from .loader import (
    PackagedWatchmanRuntime,
    UnsupportedWatchmanRuntimePlatformError,
    WatchmanRuntimeListenerTransport,
    WatchmanRuntimeSource,
    WatchmanRuntimeSourceFile,
    build_watchman_client_command,
    build_watchman_probe_command,
    build_watchman_runtime_command_prefix,
    build_watchman_runtime_environment,
    build_watchman_runtime_force_include_entries,
    build_watchman_sidecar_command,
    default_realtime_backend_for_current_install,
    default_realtime_backend_for_platform,
    hydrate_watchman_runtime_for_build,
    is_packaged_watchman_runtime_available,
    is_packaged_watchman_runtime_supported,
    listener_path_is_filesystem,
    materialize_watchman_binary,
    resolve_packaged_watchman_runtime,
)

__all__ = [
    "PackagedWatchmanRuntime",
    "WatchmanRuntimeListenerTransport",
    "WatchmanRuntimeSource",
    "WatchmanRuntimeSourceFile",
    "UnsupportedWatchmanRuntimePlatformError",
    "build_watchman_client_command",
    "build_watchman_runtime_force_include_entries",
    "build_watchman_probe_command",
    "build_watchman_runtime_command_prefix",
    "build_watchman_runtime_environment",
    "build_watchman_sidecar_command",
    "default_realtime_backend_for_current_install",
    "default_realtime_backend_for_platform",
    "hydrate_watchman_runtime_for_build",
    "is_packaged_watchman_runtime_available",
    "is_packaged_watchman_runtime_supported",
    "listener_path_is_filesystem",
    "materialize_watchman_binary",
    "resolve_packaged_watchman_runtime",
]
